### PR TITLE
New housing lottery indicators

### PR DESCRIPTION
**Pull request by SashaWeinstein**
Medium PR, would be good to have two sets of eyes on it 🎟️ 

The two new indicators are `housing_lottery_applications` and `housing_lottery_leases`. No new patterns or unexpected problems. Lots of null's at the puma level in the source data. 
Action to put the new results on DO [here](https://github.com/NYCPlanning/db-equitable-development-tool/actions/runs/3039769201)

### CODE REVIEW

**Review by mbh329 — APPROVED** [review]
LGTM, reviewed the data on the feature branch folder in DO. Accessor functions run as expected

**Review by td928 — COMMENTED** [review]
the parsing of the spreadsheet and also cleaning is definitely not an easy task and great work to do it efficiently. I suggestion here is to add the internal review functionality for the accessor to align with other indicators. Also nice to have local output for some eyeballing.

**Comment by td928** [comment]
lol looks like I am a minute too late.

**Comment by SashaWeinstein** [comment]
lol shoot I'm sorry! I figured we could just look at the outputted files on DO under the corresponding feature branch folder, it does the same thing

**Pull request merged**
