### PR TITLE
Access to Subway/SBS and Access to ADA Accessible Transit

### PR DESCRIPTION
**Pull request by SashaWeinstein**
These two indicators are similar so they are handled by the same file. They require minimal processing as they are already organized by PUMA by DCP transportation.

### CODE REVIEW

**Comment by SashaWeinstein** [comment]
Two recent commits address what we talked about in standup. Folders renamed from "QOL" to "quality_of_life", and code to clean data moved from ingest to aggregate

**Comment by SashaWeinstein** [comment]
Realized that pumas have leading zeros in internal review files, need to fix that before this gets merged

**Review by mbh329 — COMMENTED** [review]
`access_transit.py `
logic looks good except for an issue with the pct calculations - the internal review files do not match the wiki conventions. They need to be multiplied by 100 (0.123 -> 12.3) 

`assign_PUMA.py`
 `puma_to_borough` fucntion has been updated to handle 5 character puma's (this function is widely used to aggregate from puma to borough).

**Comment by SashaWeinstein** [comment]
Thanks for these comments Max, I will work on both these once the traffic indicator gets merged in as that work has code I can use for these issues

**Review by mbh329 — COMMENTED** [review]
Just looping back to this pull req as I am going through the data dictionary. The internal review files should match naming conventions as outlined in the wiki and the issue:

-  lower case naming
- acesss-ADA-pct -> access_ada
- access-subway-pct -> access_subwaysbs)

**Comment by SashaWeinstein** [comment]
Ah good catch I will work on those updates now

**Comment by SashaWeinstein** [comment]
Ok @mbh329 addressed the column label issue in new commit

**Comment by mbh329** [comment]
almost there, just need to go from ADA to ada in the column name

**Review by mbh329 — APPROVED** [review]

**Pull request merged**
