### PR TITLE
Assault Hospitalizations Indicator

### PR DESCRIPTION
**Pull request by SashaWeinstein**
Logic here is similar to pedestrian hospitalizations

### CODE REVIEW

**Review by AmandaDoyle — COMMENTED** [review]
I'd rename safety_ped_hospital_per100k to safety_pedhospital and safety_assault_hospital_per100k to safety_assaulthospital

**Review by mbh329 — APPROVED** [review]
A lot of these changes were already approved in an pull req #153. Renamed a python script and added function to handle non-fatal assaults. Csv's and naming conventions look good as well, rates follow expected pattern

**Comment by td928** [comment]
> A lot of these changes were already approved in an pull req #153. Renamed a python script and added function to handle non-fatal assaults. Csv's and naming conventions look good as well, rates follow expected pattern
@mbh329  want some clarification about your comments. Where are you seeing the column names being modified? I think Amanda comments still need to be addressed?

**Comment by td928** [comment]
> Made the column name changes. I only updated the puma file for internal review, the column label changes are the same for all geographies

those look good to me. going to approve now.

**Review by td928 — APPROVED** [review]

**Comment by mbh329** [comment]
@td928 I think amanda and I made our comments at virtually the same time

**Pull request merged**
