### PR TITLE
process new source data and export relevant categories

### PR DESCRIPTION
**Pull request by mbh329**
Update Source data related to the 2023 data updates.

Think we should decide how we want to name the processed data to match the indicator accessor name and to create a distinction between the raw source data and the (manually) processed source data. I started by uploading just two files and making the necessary changes to the ingestion and I would like feedback on naming conventions. 

One thought I had was that we can create the distinction by renaming the processed source data:

`resources/quality_of_life/COVID Deaths by race and PUMA_20230109.xlsx` -> `resources/quality_of_life/processed_covid_deaths_2023.xlsx`

At the moment, the data is processed manually and I do not change the name of the files uploaded to the `resources/` folder. Once we settle on naming conventions, we can all grab an excel sheet and process them manually and make the necessary changes to the code. 

## changes
- add and use new processed source data in `resources/`
- archive old versions of new source data by moving them to `resources/data_archive/`
- in `diabetes_self_report.py`, change to source data loading to accommodate new processed data 
- only trigger indicator tests when relevant files have changed
- in `education_outcome.py`, change source data loading to no longer expect and process data on racial group `Other`
- fix environment setup in dev container
- delete temporary copies of excel files in `resources/`

## tests
- PR tests passing
- exported categories to edm-publishing on this branch. action runs:
  - [housing_security](https://github.com/NYCPlanning/db-equitable-development-tool/actions/runs/4386277613/jobs/7680106871#step:7:57)
  - [quality_of_life](https://github.com/NYCPlanning/db-equitable-development-tool/actions/runs/4386319937/jobs/7680204444#step:7:47)

## notes
- awaiting new transportation and PUMA data. in the meantime, this work seems worth reviewing and merging
- changes in this PR should be reviewed for whether we can successfully process the new data we've been given so far
  - rather than whether the combination of new and old source data yields intended final numbers (e.g. 2020 demographics and 2021 covid data). the number of source datasets and lack of temporal overlap seems like a larger and older product concern

### CODE REVIEW

**Comment by damonmcc** [comment]
@mbh329 

I like the proposed conventions. Is this summary accurate?
- a folder in `resources/` for each indicator
- add original unaltered file
- create and rename manually processed files to align with related ingest/aggregate script
  - e.g. `resources/quality_of_life/diabetes_2023.xlsx` and `resources/quality_of_life/self_report_2023.xlsx` if they're separate files used in the same script
- use processed file filenames in ingest/aggregate scripts

**Comment by mbh329** [comment]
That wasn't exactly what I was thinking but I like that we have both the processed and unprocessed file there for reference in case we "misprocess" it

**Comment by mbh329** [comment]
Ill add in the proposed folder structure and hand this off to you if that works @damonmcc

**Comment by damonmcc** [comment]
tests passing *may* indicate that all new files are being processed. will run relevant actions to confirm

**Comment by mbh329** [comment]
Ill review now

**Comment by mbh329** [comment]
I think we need to figure out what we are expecting to get from population. Going through a review of the outputs, I noticed that for `covid_deaths` indicator and associated columns we are reporting a rate of covid deaths per group which depends on having population of each racial group as a denominator. Currently, we are using the 2020 population but if we update the population by certain geographic areas for 2021 (as supposed to 2020) than we will be getting different rates. Basically, we need to check if we should be using the 2020 population as the denom or if we should be using an updated 2021 population. If we need to use the 2021 number's, we will have to change some code and source files

**Comment by mbh329** [comment]
We need to go through the indicators and see what other data they might be dependent on. Counts are straight forward but rates/pct are obviously require a little more work

**Comment by damonmcc** [comment]
noting that one of the relevant files with 2020 population is `resources/Census_Aggregations_fromErica.csv` and it's used in `covid_death.py`

**Review by mbh329 — COMMENTED** [review]
I cant approve it FYI but it looks good to me

**Comment by damonmcc** [comment]
I'll approve in your name

**Comment by mbh329** [comment]
Thank you good sir

**Comment by damonmcc** [comment]
I, acting under the power of attorney and carrying on the duties which Max would have undertaken, I approve this PR

**Review by damonmcc — APPROVED** [review]

**Pull request merged**
